services:
  - type: web
    name: campus-connect
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "gunicorn run:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12

      - key: FLASK_ENV
        value: production

      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        sync: false
